export const FETCH_REDDITS_START = 'FETCH_REDDITS_START';
export const FETCH_REDDITS_SUCCESS = 'FETCH_REDDITS_SUCCESS';
export const FETCH_REDDITS_FAIL = 'FETCH_REDDITS_FAIL';
export const FETCH_REDDITS = 'FETCH_REDDITS';
export const SET_FILTER = 'SET_FILTER';